<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ExportMysqlSchema extends Command
{
    protected $signature = 'db:export-mysql-schema
                            {--output=deploy/mysql-schema.sql : Output file path}';

    protected $description = 'Generate a MySQL-compatible schema SQL file from current migrations';

    private const TYPE_MAP = [
        'integer'   => 'INT',
        'bigint'    => 'BIGINT',
        'smallint'  => 'SMALLINT',
        'tinyint'   => 'TINYINT',
        'mediumint' => 'MEDIUMINT',
        'real'      => 'DOUBLE',
        'float'     => 'FLOAT',
        'double'    => 'DOUBLE',
        'decimal'   => 'DECIMAL',
        'numeric'   => 'DECIMAL',
        'boolean'   => 'TINYINT(1)',
        'text'      => 'TEXT',
        'mediumtext'=> 'MEDIUMTEXT',
        'longtext'  => 'LONGTEXT',
        'blob'      => 'BLOB',
        'varchar'   => 'VARCHAR',
        'char'      => 'CHAR',
        'date'      => 'DATE',
        'datetime'  => 'DATETIME',
        'timestamp' => 'TIMESTAMP',
        'time'      => 'TIME',
        'json'      => 'JSON',
    ];

    public function handle(): int
    {
        $outputPath = base_path($this->option('output'));

        // Ensure output directory exists
        $dir = dirname($outputPath);
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $tables = $this->getTables();

        $sql = "-- MySQL schema generated by Poker Night\n";
        $sql .= "-- Generated: " . now()->toDateTimeString() . "\n";
        $sql .= "-- Source: SQLite migrations\n\n";
        $sql .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

        foreach ($tables as $table) {
            $sql .= $this->generateCreateTable($table) . "\n\n";
        }

        $sql .= "SET FOREIGN_KEY_CHECKS = 1;\n";

        file_put_contents($outputPath, $sql);

        $this->info("MySQL schema written to: {$outputPath}");
        $this->line("Tables: " . implode(', ', $tables));

        return Command::SUCCESS;
    }

    private function getTables(): array
    {
        $results = DB::select("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name");
        $skip = ['migrations', 'failed_jobs', 'jobs', 'job_batches'];
        return array_values(array_filter(
            array_map(fn($r) => $r->name, $results),
            fn($name) => ! in_array($name, $skip)
        ));
    }

    private function generateCreateTable(string $table): string
    {
        $columns = DB::select("PRAGMA table_info(`{$table}`)");
        $foreignKeys = DB::select("PRAGMA foreign_key_list(`{$table}`)");
        $indexes = DB::select("PRAGMA index_list(`{$table}`)");

        $lines = [];
        $primaryKeys = [];

        foreach ($columns as $col) {
            $line = "    `{$col->name}` " . $this->mapType($col->type, $col->name);

            if (str_contains(strtolower($col->type), 'char') && preg_match('/\((\d+)\)/', $col->type, $m)) {
                // Already has size in type
            }

            if (! $col->notnull && ! $col->pk) {
                $line .= ' NULL';
            } else {
                $line .= ' NOT NULL';
            }

            if ($col->dflt_value !== null && $col->dflt_value !== '') {
                $default = $col->dflt_value;
                if (strtoupper($default) === 'CURRENT_TIMESTAMP') {
                    $line .= ' DEFAULT CURRENT_TIMESTAMP';
                } elseif (is_numeric(trim($default, "'"))) {
                    $line .= " DEFAULT {$default}";
                } else {
                    $clean = trim($default, "'\"");
                    $line .= " DEFAULT '{$clean}'";
                }
            }

            if ($col->pk) {
                $primaryKeys[] = $col->name;
            }

            $lines[] = $line;
        }

        // Primary key
        if (count($primaryKeys) === 1) {
            $pk = $primaryKeys[0];
            $pkCol = collect($columns)->firstWhere('name', $pk);
            if ($pkCol && str_contains(strtolower($pkCol->type), 'int') && ! str_contains(strtolower($pkCol->type), 'tinyint')) {
                // Find and add AUTO_INCREMENT to column definition
                $lines = array_map(function ($line) use ($pk) {
                    if (str_starts_with($line, "    `{$pk}`")) {
                        return $line . ' AUTO_INCREMENT';
                    }
                    return $line;
                }, $lines);
            }
            $lines[] = "    PRIMARY KEY (`{$pk}`)";
        } elseif (count($primaryKeys) > 1) {
            $lines[] = '    PRIMARY KEY (`' . implode('`, `', $primaryKeys) . '`)';
        }

        // Foreign keys
        foreach ($foreignKeys as $fk) {
            $lines[] = "    CONSTRAINT `fk_{$table}_{$fk->from}` FOREIGN KEY (`{$fk->from}`) REFERENCES `{$fk->table}` (`{$fk->to}`)";
        }

        // Unique indexes
        foreach ($indexes as $idx) {
            if (! $idx->unique || $idx->origin === 'pk') continue;
            $idxCols = DB::select("PRAGMA index_info(`{$idx->name}`)");
            $colNames = array_map(fn($c) => "`{$c->name}`", $idxCols);
            $lines[] = "    UNIQUE KEY `{$idx->name}` (" . implode(', ', $colNames) . ")";
        }

        $body = implode(",\n", $lines);
        return "CREATE TABLE IF NOT EXISTS `{$table}` (\n{$body}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;";
    }

    private function mapType(string $sqliteType, string $colName = ''): string
    {
        $lower = strtolower(trim($sqliteType));

        // Exact match first to avoid datetime matching 'date'
        $exactMap = [
            'datetime'  => 'DATETIME',
            'timestamp' => 'TIMESTAMP',
            'date'      => 'DATE',
            'time'      => 'TIME',
            'text'      => 'TEXT',
            'blob'      => 'BLOB',
            'json'      => 'JSON',
            'integer'   => 'INT',
            'real'      => 'DOUBLE',
            'numeric'   => 'DECIMAL(10,2)',
            'boolean'   => 'TINYINT(1)',
        ];

        if (isset($exactMap[$lower])) {
            return $exactMap[$lower];
        }

        // Types that carry size specifiers
        if (preg_match('/^(varchar|char|decimal|numeric|float|double|int|bigint|smallint|tinyint|mediumint)(\([\d,\s]+\))?$/i', $lower, $m)) {
            $base  = strtolower($m[1]);
            $size  = $m[2] ?? '';

            if ($base === 'varchar' || $base === 'char') {
                if ($size) {
                    return strtoupper($base) . $size;
                }
                // Infer size from column name
                $isUuidColumn = $colName === 'id'
                    || str_ends_with($colName, '_id')
                    || str_ends_with($colName, '_by');

                return $isUuidColumn ? 'CHAR(32)' : 'VARCHAR(255)';
            }

            if ($base === 'tinyint') return 'TINYINT(1)';
            if ($base === 'smallint') return 'SMALLINT';
            if ($base === 'bigint') return 'BIGINT';
            if ($base === 'int' || $base === 'integer') return 'INT';
            if ($base === 'decimal' || $base === 'numeric') return $size ? "DECIMAL{$size}" : 'DECIMAL(10,2)';
        }

        return strtoupper($lower) ?: 'TEXT';
    }
}
