-- MySQL schema generated by Poker Night
-- Generated: 2026-06-06 09:30:42
-- Source: SQLite migrations

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `cache` (
    `key` VARCHAR(255) NOT NULL,
    `value` TEXT NOT NULL,
    `expiration` INT NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cache_locks` (
    `key` VARCHAR(255) NOT NULL,
    `owner` VARCHAR(255) NOT NULL,
    `expiration` INT NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `game_attendees` (
    `id` CHAR(32) NOT NULL,
    `poker_night_id` CHAR(32) NOT NULL,
    `user_id` CHAR(32) NOT NULL,
    `placement` INT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_game_attendees_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_game_attendees_poker_night_id` FOREIGN KEY (`poker_night_id`) REFERENCES `poker_nights` (`id`),
    UNIQUE KEY `game_attendees_poker_night_id_user_id_unique` (`poker_night_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `game_images` (
    `id` CHAR(32) NOT NULL,
    `poker_night_id` CHAR(32) NOT NULL,
    `uploaded_by` CHAR(32) NOT NULL,
    `file_path` VARCHAR(255) NOT NULL,
    `caption` VARCHAR(255) NULL,
    `is_cover` TINYINT(1) NOT NULL DEFAULT '0',
    `sort_order` INT NOT NULL DEFAULT '0',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_game_images_uploaded_by` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_game_images_poker_night_id` FOREIGN KEY (`poker_night_id`) REFERENCES `poker_nights` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `group_members` (
    `id` CHAR(32) NOT NULL,
    `group_id` CHAR(32) NOT NULL,
    `user_id` CHAR(32) NOT NULL,
    `role` VARCHAR(255) NOT NULL DEFAULT 'MEMBER',
    `joined_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_group_members_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_group_members_group_id` FOREIGN KEY (`group_id`) REFERENCES `poker_groups` (`id`),
    UNIQUE KEY `group_members_group_id_user_id_unique` (`group_id`, `user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `poker_groups` (
    `id` CHAR(32) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT NULL,
    `owner_id` CHAR(32) NOT NULL,
    `invite_code` VARCHAR(255) NOT NULL,
    `isActive` TINYINT(1) NOT NULL DEFAULT '1',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_poker_groups_owner_id` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`),
    UNIQUE KEY `poker_groups_invite_code_unique` (`invite_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `poker_nights` (
    `id` CHAR(32) NOT NULL,
    `group_id` CHAR(32) NOT NULL,
    `created_by` CHAR(32) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `notes` TEXT NULL,
    `scheduled_at` DATETIME NOT NULL,
    `played_at` DATETIME NULL,
    `status` VARCHAR(255) NOT NULL DEFAULT 'SCHEDULED',
    `buy_in` DECIMAL(10,2) NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_poker_nights_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
    CONSTRAINT `fk_poker_nights_group_id` FOREIGN KEY (`group_id`) REFERENCES `poker_groups` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `users` (
    `id` CHAR(32) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role` VARCHAR(255) NOT NULL DEFAULT 'USER',
    `isActive` TINYINT(1) NOT NULL DEFAULT '1',
    `avatar_url` VARCHAR(255) NULL,
    `remember_token` VARCHAR(255) NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `users_email_unique` (`email`),
    UNIQUE KEY `users_username_unique` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
